"""
Full trace of data flow for the CH number bug.
"""

print("=" * 80)
print("FULL DATA FLOW TRACE")
print("=" * 80)

print("\n🏢 ENTERPRISE LIMITED (06134591) Enrichment")
print("=" * 80)

print("\n1️⃣ build_ownership_tree(company_number='06134591', depth=0)")
print("   Parameters:")
print("   - company_number = '06134591'")
print("   - company_name = 'ENTERPRISE LIMITED'")
print()
print("   Extracted shareholders from CS01:")
print("   - AMEY LIMITED (100%)")
print()
print("   Processing shareholder: AMEY LIMITED")
print("   - Line 684-692: Create shareholder_info = {}")
print("   - Line 700-708: company_search = search_company_by_name('AMEY LIMITED')")
print("   - Line 709: child_company_number = '02379479' ✅")
print("   - Line 711: shareholder_info['company_number'] = '02379479' ✅")
print()
print("   - Line 750-756: Recursive call:")
print("     build_ownership_tree(company_number='02379479', depth=1)")
print("     Returns child_tree with Amey's shareholders")
print()
print("   - Line 758: shareholder_info['children'] = child_tree.get('shareholders', [])")
print("     This copies Amey's shareholders into shareholder_info['children']")
print()
print("   - Line 786: processed_shareholders.append(shareholder_info)")
print()
print("   - Line 788-795: Return:")
print("     {")
print("       'company_number': '06134591',  # PARENT")
print("       'company_name': 'ENTERPRISE LIMITED',")
print("       'shareholders': [")
print("         {")
print("           'name': 'AMEY LIMITED',")
print("           'company_number': '02379479',  # CHILD ✅")
print("           'percentage': 100.0,")
print("           'children': [...]  # Amey's shareholders")
print("         }")
print("       ]")
print("     }")

print("\n" + "=" * 80)
print("\n2️⃣ Tree stored in database as ownership_tree_json")
print("   The tree structure above is JSON-serialized and stored.")

print("\n" + "=" * 80)
print("\n3️⃣ build_screening_list() reads the tree")
print("   - Line 2928: shareholders_in_node = tree_node.get('shareholders', [])")
print("   - Line 2931: for sh in shareholders_in_node:")
print("   - Line 2936: shareholder_company_number = sh.get('company_number')")
print("     Should be: '02379479' ✅")

print("\n" + "=" * 80)
print("\n❓ WHERE IS THE BUG?")
print("=" * 80)
print("The logic looks CORRECT everywhere!")
print()
print("Possible causes:")
print("1. Database corruption: ownership_tree_json has wrong data")
print("2. Frontend bug: Displaying wrong company name/number")
print("3. Tree flattening bug: extract_ownership_chain() has a bug")
print("4. Recursive processing bug: Child company overwrites parent data")

print("\n🔍 NEXT STEP:")
print("Check if there's a 'children' vs 'shareholders' field confusion")
print("Or check if recursive call is overwriting shareholder_info")

print("\n" + "=" * 80)
